config/routes.rb
EngVote::Application.routes.draw do
  devise_for :voters

  resources :voters
  resource :voter_session
  resource :account
  root :to => 'elections#public'
  match 'help' => 'elections#help'
  match 'vote' => 'voter_sessions#new'
  match 'admin' => 'elections#admin'
  match 'elections' => 'elections#index'
  match 'elections/new' => 'elections#new'
  match 'elections/create' => 'elections#create'
  match 'elections/update' => 'elections#update'
  match 'elections/vote' => 'votes#create'
  match 'election/add_choice' => 'elections#add_choice'
  match 'elections/:id/:action' => 'elections#index'
  match 'public' => 'elections#public'

end

app/views/layouts/application.html.haml
!!! Strict

%html(xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en")

%p.notice
  = notice

%p.alert
  = alert

%head
  %meta(http-equiv="content-type" content="text/html;charset=UTF-8")

  %title= render :partial => "partials/title"

  = stylesheet_link_tag 'screen.css'
  = javascript_include_tag 'application'

  - if controller.action_name == "vote"
    %script(type="text/javascript")
      Event.observe(window, 'load', vote_system);

%body(class="#{controller.action_name}")
  %p(style="color: green")= flash[:notice]

  %h1= link_to "EngVote", "/", :title => 'Back to Home Screen'

  %ul#menu
    %li= link_to "Home", "/"
    %li= link_to "Help", :controller => "elections", :action => 'help'
    -if current_voter
      %li= link_to "Sign Out", voter_session_path, :method => :delete

  %div#content
    = yield
    %br(style="clear: both")
  - if Rails.env.to_s == "development"
    =debug(current_voter)